import type { EntidadKey, DefinicionEntidad } from './tipos'

// Mismos campos que las funciones "rápidas" ya existentes (lib/proveedores.ts,
// lib/compradores.ts, lib/cuentasPropias.ts) — a propósito el mismo shape
// que ya usan los selectores del panel, para no mantener dos descripciones
// de "qué es un proveedor/cliente/cuenta" que puedan divergir.
export const CATALOGO_ENTIDADES: Record<EntidadKey, DefinicionEntidad> = {
  proveedor: {
    key: 'proveedor',
    label: 'Proveedor',
    modulo: 'proveedores',
    rutaNavegacion: '/admin/proveedores',
    campos: [
      { nombre: 'razon_social', label: 'Razón social', requerido: true, descripcion: 'Nombre o razón social del proveedor' },
      { nombre: 'cuit', label: 'CUIT', requerido: false, descripcion: 'Formato 20-12345678-9' },
      { nombre: 'telefono', label: 'Teléfono', requerido: false },
      { nombre: 'email', label: 'Email', requerido: false },
      { nombre: 'direccion', label: 'Dirección', requerido: false },
      { nombre: 'notas', label: 'Notas', requerido: false },
    ],
  },
  cliente: {
    key: 'cliente',
    label: 'Cliente',
    modulo: 'clientes',
    rutaNavegacion: '/admin/clientes',
    campos: [
      { nombre: 'nombre_completo', label: 'Nombre completo', requerido: true, descripcion: 'Nombre y apellido, o razón social' },
      { nombre: 'dni_cuit', label: 'CUIT/DNI', requerido: false },
      { nombre: 'telefono', label: 'Teléfono', requerido: false },
      { nombre: 'email', label: 'Email', requerido: false },
    ],
  },
  cuenta_propia: {
    key: 'cuenta_propia',
    label: 'Cuenta propia',
    modulo: 'cuentas',
    rutaNavegacion: '/admin/cuentas',
    campos: [
      { nombre: 'nombre', label: 'Nombre', requerido: true, descripcion: 'Ej: "Banco Galicia", "Caja obra Norte"' },
      { nombre: 'tipo', label: 'Tipo', requerido: true, opciones: ['banco', 'caja'] },
      { nombre: 'moneda', label: 'Moneda', requerido: true, opciones: ['ARS', 'USD'] },
      { nombre: 'obra_id', label: 'Proyecto', requerido: false, descripcion: 'Id real del proyecto, obtenido de listar_proyectos — opcional. Si se omite, es una cuenta de la empresa (sin proyecto), y eso solo lo puede crear un administrador. Si se indica, la puede crear cualquiera con el módulo Cuentas habilitado en ese proyecto.' },
    ],
  },
  categoria_gasto: {
    key: 'categoria_gasto',
    label: 'Categoría de gasto',
    modulo: 'gastos',
    rutaNavegacion: '/admin/gastos',
    campos: [
      { nombre: 'nombre', label: 'Nombre', requerido: true, descripcion: 'Ej: "Materiales", "Honorarios profesionales"' },
    ],
  },
  persona: {
    key: 'persona',
    label: 'Persona',
    modulo: 'personal',
    rutaNavegacion: '/admin/personal',
    campos: [
      { nombre: 'nombre', label: 'Nombre', requerido: true },
      { nombre: 'dni', label: 'DNI', requerido: false },
      { nombre: 'cuil', label: 'CUIL', requerido: false },
      { nombre: 'telefono', label: 'Teléfono', requerido: false },
      { nombre: 'tipo_contratacion', label: 'Tipo de contratación', requerido: false, opciones: ['relacion_dependencia', 'contratado', 'subcontratista'] },
      { nombre: 'categoria', label: 'Categoría/oficio', requerido: false, descripcion: 'Ej: "Albañil", "Electricista"' },
      { nombre: 'jornal', label: 'Jornal', requerido: false, descripcion: 'Monto del jornal diario' },
    ],
  },
  cuadrilla: {
    key: 'cuadrilla',
    label: 'Cuadrilla',
    modulo: 'personal',
    rutaNavegacion: '/admin/personal',
    campos: [
      { nombre: 'nombre', label: 'Nombre', requerido: true, descripcion: 'Ej: "Cuadrilla 1", "Equipo de albañilería"' },
      { nombre: 'notas', label: 'Notas', requerido: false },
    ],
  },
  gasto: {
    key: 'gasto',
    label: 'Gasto',
    modulo: 'gastos',
    rutaNavegacion: '/admin/gastos',
    campos: [
      { nombre: 'descripcion', label: 'Descripción', requerido: true },
      { nombre: 'monto', label: 'Monto', requerido: true, descripcion: 'Monto total del gasto (número)' },
      { nombre: 'moneda', label: 'Moneda', requerido: false, opciones: ['ARS', 'USD'], descripcion: 'Si se omite, ARS' },
      { nombre: 'obra_id', label: 'Proyecto', requerido: false, descripcion: 'Id real del proyecto al que se imputa, obtenido de listar_proyectos. Si se omite queda como gasto administrativo de la empresa (sin proyecto) — eso solo lo puede cargar un administrador.' },
      { nombre: 'proveedor_id', label: 'Proveedor', requerido: false, descripcion: 'Id real del proveedor, obtenido de listar_proveedores' },
      { nombre: 'cuenta_proveedor_id', label: 'Cuenta del proveedor', requerido: false, descripcion: 'Id real de la cuenta (CBU/Alias/Efectivo/Cheque/Otro) del proveedor donde se le paga, obtenida de listar_cuentas_proveedor — solo tiene sentido si ya hay un proveedor elegido' },
      { nombre: 'categoria_id', label: 'Categoría', requerido: false, descripcion: 'Id real de la categoría de gasto, obtenido de listar_categorias_gasto' },
      { nombre: 'certificado_id', label: 'Certificado (pago a subcontratista)', requerido: false, descripcion: 'Id real de un certificado de avance de un contrato con SUBCONTRATISTA que este gasto está pagando, obtenido de listar_certificados_pago_proveedor — solo aplica cuando el proveedor es un subcontratista con contrato y certificados propios' },
      { nombre: 'numero_comprobante', label: 'Número de comprobante', requerido: false, descripcion: 'Número de factura/recibo, si el usuario lo tiene' },
      { nombre: 'monto_neto', label: 'Monto neto (sin IVA)', requerido: false, descripcion: 'Desglose informativo — no afecta ningún cálculo real de caja/tesorería, solo queda de referencia' },
      { nombre: 'iva', label: 'IVA', requerido: false, descripcion: 'Desglose informativo — no afecta ningún cálculo real de caja/tesorería' },
      { nombre: 'percepciones', label: 'Percepciones', requerido: false, descripcion: 'Desglose informativo — no afecta ningún cálculo real de caja/tesorería' },
      { nombre: 'fecha_vencimiento', label: 'Fecha de vencimiento', requerido: false, descripcion: 'Formato YYYY-MM-DD — si se omite, hoy' },
      { nombre: 'notas', label: 'Notas', requerido: false },
    ],
  },
  orden_compra: {
    key: 'orden_compra',
    label: 'Orden de compra',
    modulo: 'compras',
    rutaNavegacion: '/admin/compras?tab=ordenes',
    campos: [
      { nombre: 'obra_id', label: 'Proyecto', requerido: false, descripcion: 'Id real del proyecto, obtenido de listar_proyectos. Si se omite, la orden queda en el pool de la empresa para repartir después entre obras.' },
      { nombre: 'items', label: 'Ítems', requerido: true, descripcion: 'Lista de productos pedidos, cada uno con nombre y cantidad (y unidad de medida si corresponde) — al menos uno. Si el producto no existe todavía en el sistema, se crea solo.' },
      { nombre: 'fecha_emision', label: 'Fecha de emisión', requerido: false, descripcion: 'Formato YYYY-MM-DD — si se omite, hoy' },
      { nombre: 'notas', label: 'Notas', requerido: false },
    ],
  },
  certificado_avance: {
    key: 'certificado_avance',
    label: 'Certificado de avance',
    modulo: 'certificados',
    rutaNavegacion: '/admin/proyectos/{obraId}/certificados',
    campos: [
      { nombre: 'contrato_id', label: 'Contrato', requerido: true, descripcion: 'Id real del contrato, obtenido de listar_contratos_obra' },
      { nombre: 'periodo', label: 'Período', requerido: true, descripcion: 'Ej: "Enero 2026", "Semana del 1 al 15/03"' },
      { nombre: 'items', label: 'Avance por rubro', requerido: true, descripcion: 'Nuevo % de avance ACUMULADO (no incremental) para cada rubro que cambió — obtené los rubros y su avance actual con consultar_rubros_contrato antes. Los rubros no mencionados quedan con el mismo % que ya tenían.' },
      { nombre: 'descripcion_avances', label: 'Descripción de los avances', requerido: false },
      { nombre: 'notas', label: 'Notas', requerido: false },
    ],
  },
  pago_gasto: {
    key: 'pago_gasto',
    label: 'Pago de un gasto',
    modulo: 'gastos',
    rutaNavegacion: '/admin/gastos',
    campos: [
      { nombre: 'gasto_id', label: 'Gasto', requerido: true, descripcion: 'Id real del gasto pendiente, obtenido de listar_gastos_pendientes' },
      { nombre: 'cuenta_propia_id', label: 'Cuenta', requerido: true, descripcion: 'Id real de la cuenta desde la que se paga, obtenida de listar_cuentas_disponibles_gasto — no cualquier cuenta de la empresa sirve, depende del proyecto del gasto' },
      { nombre: 'fecha_pago', label: 'Fecha de pago', requerido: false, descripcion: 'Formato YYYY-MM-DD — si se omite, hoy' },
      { nombre: 'resumen', label: 'Resumen', requerido: true, descripcion: 'Frase corta y legible con lo que se va a pagar y con qué cuenta, ej. "Factura Proveedor ABC — $50.000 ARS, con Banco Nación" — armala con los datos que ya te devolvieron listar_gastos_pendientes/listar_cuentas_disponibles_gasto. Es lo único que el usuario lee para verificar antes de confirmar, los ids no se muestran.' },
    ],
  },
  cobro: {
    key: 'cobro',
    label: 'Cobro',
    modulo: 'cobros',
    rutaNavegacion: '/admin/proyectos/{obraId}/cobros',
    campos: [
      { nombre: 'contrato_id', label: 'Contrato', requerido: true, descripcion: 'Id real del contrato con el cliente, obtenido de listar_contratos_obra — solo aplica a contratos tipo "cliente", no a subcontratistas' },
      { nombre: 'certificado_id', label: 'Certificado', requerido: false, descripcion: 'Id real del certificado que se cobra, obtenido de listar_certificados_contrato — OPCIONAL: un cobro puede no venir de ningún certificado (ej. un anticipo o seña cobrado antes de certificar avance). Omitir si no aplica.' },
      { nombre: 'monto', label: 'Monto', requerido: true, descripcion: 'Monto del cobro (número)' },
      { nombre: 'moneda', label: 'Moneda', requerido: false, opciones: ['ARS', 'USD'], descripcion: 'Si se omite, la del contrato' },
      { nombre: 'fecha_vencimiento', label: 'Fecha de vencimiento', requerido: false, descripcion: 'Formato YYYY-MM-DD — si se omite, hoy' },
      { nombre: 'notas', label: 'Notas', requerido: false, descripcion: 'Útil para aclarar el origen cuando no hay certificado, ej. "Anticipo", "Seña"' },
    ],
  },
  pago_cobro: {
    key: 'pago_cobro',
    label: 'Registrar cobro efectivo',
    modulo: 'cobros',
    rutaNavegacion: '/admin/proyectos/{obraId}/cobros',
    campos: [
      { nombre: 'cobro_id', label: 'Cobro', requerido: true, descripcion: 'Id real del cobro pendiente, obtenido de listar_cobros_pendientes' },
      { nombre: 'cuenta_propia_id', label: 'Cuenta', requerido: true, descripcion: 'Id real de la cuenta a la que entró la plata, obtenida de listar_cuentas_disponibles_cobro' },
      { nombre: 'fecha_pago', label: 'Fecha de cobro', requerido: false, descripcion: 'Formato YYYY-MM-DD — si se omite, hoy' },
      { nombre: 'resumen', label: 'Resumen', requerido: true, descripcion: 'Frase corta y legible con lo que se va a cobrar y con qué cuenta, ej. "José Ramón Vidal — 174.590 USD, con Banco Francés" — armala con los datos que ya te devolvieron listar_cobros_pendientes/listar_cuentas_disponibles_cobro. Es lo único que el usuario lee para verificar antes de confirmar, los ids no se muestran.' },
    ],
  },
  presupuesto: {
    key: 'presupuesto',
    label: 'Presupuesto',
    modulo: 'presupuestos',
    rutaNavegacion: '/admin/presupuestos',
    campos: [
      { nombre: 'cliente_nombre', label: 'Cliente', requerido: true, descripcion: 'Nombre del cliente para el que se cotiza — no hace falta que ya exista como comprador, se guarda como texto simple' },
      { nombre: 'cliente_cuit', label: 'CUIT/DNI del cliente', requerido: false },
      { nombre: 'cliente_email', label: 'Email del cliente', requerido: false },
      { nombre: 'cliente_telefono', label: 'Teléfono del cliente', requerido: false },
      { nombre: 'items', label: 'Ítems por rubro', requerido: true, descripcion: 'Lista de rubros cotizados, cada uno con rubro, cantidad y precio unitario — al menos uno. El rubro se resuelve o crea solo por nombre.' },
      { nombre: 'moneda', label: 'Moneda', requerido: false, opciones: ['ARS', 'USD'], descripcion: 'Si se omite, ARS' },
      { nombre: 'fecha_inicio', label: 'Fecha de inicio estimada', requerido: false },
      { nombre: 'fecha_fin_estimada', label: 'Fecha de fin estimada', requerido: false },
      { nombre: 'descripcion', label: 'Descripción', requerido: false },
      { nombre: 'notas', label: 'Notas', requerido: false },
    ],
  },
  equipo: {
    key: 'equipo',
    label: 'Equipo',
    modulo: 'inventario',
    rutaNavegacion: '/admin/inventario',
    campos: [
      { nombre: 'nombre', label: 'Nombre', requerido: true, descripcion: 'Ej: "Excavadora CAT 320", "Taladro Bosch"' },
      { nombre: 'tipo', label: 'Tipo', requerido: false, descripcion: 'Texto libre — ej: "Herramienta", "Vehículo", "Maquinaria pesada"' },
      { nombre: 'marca', label: 'Marca', requerido: false },
      { nombre: 'modelo', label: 'Modelo', requerido: false },
      { nombre: 'nro_serie', label: 'N° de serie', requerido: false },
      { nombre: 'notas', label: 'Notas', requerido: false },
    ],
  },
  asignacion_equipo: {
    key: 'asignacion_equipo',
    label: 'Asignar equipo a proyecto',
    modulo: 'inventario',
    rutaNavegacion: '/admin/inventario',
    campos: [
      { nombre: 'equipo_id', label: 'Equipo', requerido: true, descripcion: 'Id real del equipo, obtenido de listar_equipos' },
      { nombre: 'obra_id', label: 'Proyecto', requerido: true, descripcion: 'Id real del proyecto, obtenido de listar_proyectos' },
      { nombre: 'resumen', label: 'Resumen', requerido: true, descripcion: 'Frase corta y legible, ej. "Excavadora CAT 320 → obra Norte" — es lo único que ve el usuario para verificar antes de confirmar, los ids no se muestran.' },
    ],
  },
  liberacion_equipo: {
    key: 'liberacion_equipo',
    label: 'Cambiar estado de equipo',
    modulo: 'inventario',
    rutaNavegacion: '/admin/inventario',
    campos: [
      { nombre: 'equipo_id', label: 'Equipo', requerido: true, descripcion: 'Id real del equipo, obtenido de listar_equipos' },
      { nombre: 'nuevo_estado', label: 'Nuevo estado', requerido: true, opciones: ['disponible', 'mantenimiento', 'baja'] },
      { nombre: 'resumen', label: 'Resumen', requerido: true, descripcion: 'Frase corta y legible, ej. "Excavadora CAT 320 → disponible (devuelta de obra Norte)" — es lo único que ve el usuario para verificar antes de confirmar.' },
    ],
  },
  reserva: {
    key: 'reserva',
    label: 'Reserva',
    modulo: 'reservas',
    rutaNavegacion: '/admin/proyectos/{obraId}/reservas',
    campos: [
      { nombre: 'unidad_id', label: 'Unidad', requerido: true, descripcion: 'Id real de la unidad, obtenida de listar_unidades_disponibles — tiene que estar en estado Disponible' },
      { nombre: 'comprador_id', label: 'Cliente existente', requerido: false, descripcion: 'Id real de un cliente ya cargado, obtenido de listar_clientes — si se omite, hace falta cliente_nombre para crear uno nuevo' },
      { nombre: 'cliente_nombre', label: 'Nombre del cliente nuevo', requerido: false, descripcion: 'Requerido si no se da comprador_id — crea un cliente nuevo con este nombre' },
      { nombre: 'cliente_dni_cuit', label: 'CUIT/DNI del cliente nuevo', requerido: false },
      { nombre: 'cliente_email', label: 'Email del cliente nuevo', requerido: false },
      { nombre: 'cliente_telefono', label: 'Teléfono del cliente nuevo', requerido: false },
      { nombre: 'fecha_vencimiento', label: 'Vence el', requerido: false, descripcion: 'Formato YYYY-MM-DD — si se omite, hoy + 30 días' },
      { nombre: 'monto_sena', label: 'Seña (USD)', requerido: false, descripcion: 'Monto de la seña — la venta de unidades es siempre en dólares, opcional' },
      { nombre: 'cuenta_propia_id', label: 'Cuenta', requerido: false, descripcion: 'Id real de la cuenta (siempre USD) donde entra la seña, obtenida de listar_cuentas_desarrollo — opcional' },
      { nombre: 'notas', label: 'Notas', requerido: false },
      { nombre: 'resumen', label: 'Resumen', requerido: true, descripcion: 'Frase corta y legible con qué unidad y para quién, ej. "Piso 3 depto B — reserva para Juan Pérez, seña USD 5.000" — armala con los datos que ya tenés de listar_unidades_disponibles/listar_clientes. Es lo único que el usuario lee para verificar antes de confirmar, los ids no se muestran.' },
    ],
  },
  contrato_venta: {
    key: 'contrato_venta',
    label: 'Contrato de venta',
    modulo: 'contratos',
    rutaNavegacion: '/admin/proyectos/{obraId}/contratos',
    campos: [
      { nombre: 'unidad_id', label: 'Unidad', requerido: true, descripcion: 'Id real de la unidad, obtenida de listar_unidades_disponibles' },
      { nombre: 'reserva_id', label: 'Reserva de origen', requerido: false, descripcion: 'Id real de una reserva Vigente de esa misma unidad, si la venta viene de una reserva — toma el cliente y la seña de ahí como base' },
      { nombre: 'comprador_id', label: 'Cliente existente', requerido: false, descripcion: 'Id real de un cliente ya cargado, obtenido de listar_clientes — se omite si viene de reserva_id o si se da cliente_nombre' },
      { nombre: 'cliente_nombre', label: 'Nombre del cliente nuevo', requerido: false, descripcion: 'Solo si no hay reserva_id ni comprador_id' },
      { nombre: 'cliente_dni_cuit', label: 'CUIT/DNI del cliente nuevo', requerido: false },
      { nombre: 'cliente_email', label: 'Email del cliente nuevo', requerido: false },
      { nombre: 'cliente_telefono', label: 'Teléfono del cliente nuevo', requerido: false },
      { nombre: 'precio_final', label: 'Precio final (USD)', requerido: false, descripcion: 'Si se omite, el precio de lista de la unidad' },
      { nombre: 'entrega_efectiva', label: 'Entrega inicial (USD)', requerido: false, descripcion: 'Si se omite, el mínimo de entrega de la unidad (o la seña de la reserva si es mayor)' },
      { nombre: 'cantidad_cuotas', label: 'Cantidad de cuotas', requerido: false, descripcion: 'Si se omite, el máximo permitido para esa unidad. Las cuotas se generan solas, no hace falta cargarlas.' },
      { nombre: 'fecha_firma', label: 'Fecha de firma', requerido: false, descripcion: 'Formato YYYY-MM-DD — si se omite, hoy' },
      { nombre: 'cuenta_propia_id', label: 'Cuenta', requerido: false, descripcion: 'Id real de la cuenta (siempre USD), obtenida de listar_cuentas_desarrollo — si se omite y viene de una reserva, se usa la misma cuenta de la reserva' },
      { nombre: 'notas', label: 'Notas', requerido: false },
      { nombre: 'resumen', label: 'Resumen', requerido: true, descripcion: 'Frase corta y legible con qué unidad, para quién y en cuántas cuotas, ej. "Piso 3 depto B — venta a Juan Pérez, USD 120.000 en 24 cuotas". Es lo único que el usuario lee para verificar antes de confirmar, los ids no se muestran.' },
    ],
  },
  tipologia: {
    key: 'tipologia',
    label: 'Tipología',
    modulo: 'tipologias',
    rutaNavegacion: '/admin/proyectos/{obraId}/tipologias',
    campos: [
      { nombre: 'obra_id', label: 'Proyecto', requerido: true, descripcion: 'Id real del proyecto (tipo desarrollo), obtenido de listar_proyectos' },
      { nombre: 'nombre', label: 'Nombre', requerido: true, descripcion: 'Ej: "2 ambientes con balcón", "Monoambiente"' },
      { nombre: 'm2_propios', label: 'M² propios', requerido: true, descripcion: 'Metros cuadrados propios (número)' },
      { nombre: 'm2_comunes', label: 'M² comunes', requerido: false, descripcion: 'Si se omite, 0' },
      { nombre: 'descripcion', label: 'Descripción', requerido: false },
    ],
  },
  unidad: {
    key: 'unidad',
    label: 'Unidad',
    modulo: 'unidades',
    rutaNavegacion: '/admin/proyectos/{obraId}/unidades',
    campos: [
      { nombre: 'obra_id', label: 'Proyecto', requerido: true, descripcion: 'Id real del proyecto (tipo desarrollo), obtenido de listar_proyectos' },
      { nombre: 'tipologia_id', label: 'Tipología', requerido: true, descripcion: 'Id real de la tipología, obtenida de listar_tipologias — si no existe ninguna que corresponda, hay que crearla primero con crear_tipologia' },
      { nombre: 'piso', label: 'Piso', requerido: true, descripcion: 'Número de piso (entero)' },
      { nombre: 'numero', label: 'Número/identificador', requerido: true, descripcion: 'Ej: "301", "A"' },
      { nombre: 'letra', label: 'Letra', requerido: false, descripcion: 'Solo si el edificio distingue unidades por letra además de número — la mayoría no la usa' },
      { nombre: 'orientacion', label: 'Orientación', requerido: false, descripcion: 'Ej: "Norte", "Frente", "Contrafrente"' },
      { nombre: 'm2', label: 'M²', requerido: false, descripcion: 'Si se omite, queda sin especificar (se toma como referencia el de la tipología)' },
      { nombre: 'precio_lista', label: 'Precio de lista (USD)', requerido: true },
      { nombre: 'entrega_minima_pct', label: '% de entrega mínima', requerido: false, descripcion: 'Si se omite, 30' },
      { nombre: 'max_cuotas', label: 'Cuotas máximas', requerido: false, descripcion: 'Si se omite, 36' },
    ],
  },
  asignacion_personal: {
    key: 'asignacion_personal',
    label: 'Asignar persona a proyecto',
    modulo: 'personal',
    rutaNavegacion: '/admin/personal',
    campos: [
      { nombre: 'personal_id', label: 'Persona', requerido: true, descripcion: 'Id real de la persona, obtenido de listar_personal' },
      { nombre: 'obra_id', label: 'Proyecto', requerido: true, descripcion: 'Id real del proyecto, obtenido de listar_proyectos' },
      { nombre: 'resumen', label: 'Resumen', requerido: true, descripcion: 'Frase corta y legible, ej. "Juan Pérez → obra Norte" — es lo único que ve el usuario para verificar antes de confirmar, los ids no se muestran.' },
    ],
  },
  liberacion_personal: {
    key: 'liberacion_personal',
    label: 'Cambiar estado de persona',
    modulo: 'personal',
    rutaNavegacion: '/admin/personal',
    campos: [
      { nombre: 'personal_id', label: 'Persona', requerido: true, descripcion: 'Id real de la persona, obtenido de listar_personal' },
      { nombre: 'nuevo_estado', label: 'Nuevo estado', requerido: true, opciones: ['disponible', 'licencia', 'baja'] },
      { nombre: 'resumen', label: 'Resumen', requerido: true, descripcion: 'Frase corta y legible, ej. "Juan Pérez → disponible (devuelto de obra Norte)" — es lo único que ve el usuario para verificar antes de confirmar.' },
    ],
  },
  asignacion_cuadrilla: {
    key: 'asignacion_cuadrilla',
    label: 'Asignar cuadrilla a proyecto',
    modulo: 'personal',
    rutaNavegacion: '/admin/personal',
    campos: [
      { nombre: 'cuadrilla_id', label: 'Cuadrilla', requerido: true, descripcion: 'Id real de la cuadrilla, obtenido de listar_cuadrillas' },
      { nombre: 'obra_id', label: 'Proyecto', requerido: true, descripcion: 'Id real del proyecto, obtenido de listar_proyectos' },
      { nombre: 'resumen', label: 'Resumen', requerido: true, descripcion: 'Frase corta y legible, ej. "Cuadrilla Techos → obra Norte (5 personas)" — es lo único que ve el usuario para verificar antes de confirmar.' },
    ],
  },
  cancelacion_reserva: {
    key: 'cancelacion_reserva',
    label: 'Cancelar reserva',
    modulo: 'reservas',
    rutaNavegacion: '/admin/proyectos/{obraId}/reservas',
    campos: [
      { nombre: 'unidad_id', label: 'Unidad', requerido: true, descripcion: 'Id real de la unidad reservada, obtenida de listar_unidades_disponibles con estado="Reservado"' },
      { nombre: 'resumen', label: 'Resumen', requerido: true, descripcion: 'Frase corta y legible, ej. "Piso 3 depto B — cancelar reserva de Juan Pérez" — es lo único que ve el usuario para verificar antes de confirmar.' },
    ],
  },
  cuenta_proveedor: {
    key: 'cuenta_proveedor',
    label: 'Cuenta de proveedor',
    modulo: 'proveedores',
    rutaNavegacion: '/admin/proveedores',
    campos: [
      { nombre: 'proveedor_id', label: 'Proveedor', requerido: true, descripcion: 'Id real del proveedor, obtenido de listar_proveedores' },
      { nombre: 'tipo', label: 'Tipo', requerido: false, opciones: ['CBU', 'Alias', 'Efectivo', 'Cheque', 'Otro'], descripcion: 'Si se omite, CBU' },
      { nombre: 'denominacion', label: 'Denominación', requerido: false, descripcion: 'Ej: nombre del titular o del banco' },
      { nombre: 'numero', label: 'Número/CBU/Alias', requerido: false },
      { nombre: 'moneda', label: 'Moneda', requerido: false, opciones: ['ARS', 'USD'], descripcion: 'Si se omite, ARS' },
    ],
  },
  recepcion_compra: {
    key: 'recepcion_compra',
    label: 'Recepción de una orden de compra',
    modulo: 'compras',
    rutaNavegacion: '/admin/compras?tab=ordenes',
    campos: [
      { nombre: 'orden_compra_id', label: 'Orden de compra', requerido: true, descripcion: 'Id real de la orden, obtenido de listar_ordenes_compra' },
      { nombre: 'proveedor_id', label: 'Proveedor', requerido: true, descripcion: 'Id real del proveedor que entregó, obtenido de listar_proveedores' },
      { nombre: 'items', label: 'Ítems recibidos', requerido: true, descripcion: 'Lista de qué se recibió de esta orden — cada uno con el id del ítem (obtenido de listar_items_pendientes_orden), la cantidad recibida y el precio unitario pagado. Al menos uno.' },
      { nombre: 'fecha', label: 'Fecha de recepción', requerido: false, descripcion: 'Formato YYYY-MM-DD — si se omite, hoy' },
      { nombre: 'numero_comprobante', label: 'Número de comprobante', requerido: false },
      { nombre: 'iva', label: 'IVA', requerido: false, descripcion: 'Desglose informativo, se copia al gasto que se genera' },
      { nombre: 'percepciones', label: 'Percepciones', requerido: false, descripcion: 'Desglose informativo, se copia al gasto que se genera' },
      { nombre: 'notas', label: 'Notas', requerido: false },
      { nombre: 'resumen', label: 'Resumen', requerido: true, descripcion: 'Frase corta y legible con qué orden y qué se recibió, ej. "Orden #12 — recepción de 100 bolsas de cemento de Proveedor ABC". Es lo único que el usuario lee para verificar antes de confirmar, los ids no se muestran.' },
    ],
  },
  reparto_stock: {
    key: 'reparto_stock',
    label: 'Repartir stock entre proyectos',
    modulo: 'compras',
    rutaNavegacion: '/admin/compras?tab=stock',
    campos: [
      { nombre: 'producto_id', label: 'Producto', requerido: true, descripcion: 'Id real del producto, obtenido de listar_stock' },
      { nombre: 'obra_origen', label: 'Proyecto de origen', requerido: false, descripcion: 'Id real del proyecto de donde sale el stock, obtenido de listar_proyectos — si se omite, sale del pool de la empresa' },
      { nombre: 'obra_destino', label: 'Proyecto de destino', requerido: false, descripcion: 'Id real del proyecto al que entra el stock, obtenido de listar_proyectos — si se omite, entra al pool de la empresa' },
      { nombre: 'cantidad', label: 'Cantidad', requerido: true, descripcion: 'Cantidad a repartir (número)' },
      { nombre: 'resumen', label: 'Resumen', requerido: true, descripcion: 'Frase corta y legible, ej. "50 bolsas de cemento — pool de empresa → obra Norte". Es lo único que el usuario lee para verificar antes de confirmar, los ids no se muestran.' },
    ],
  },
  acopio: {
    key: 'acopio',
    label: 'Acopio',
    modulo: 'compras',
    rutaNavegacion: '/admin/compras?tab=acopios',
    campos: [
      { nombre: 'obra_id', label: 'Proyecto', requerido: false, descripcion: 'Id real del proyecto, obtenido de listar_proyectos — si se omite, es un acopio administrativo de la empresa (sin proyecto), y eso solo lo puede crear un administrador' },
      { nombre: 'proveedor_id', label: 'Proveedor', requerido: true, descripcion: 'Id real del proveedor con el que se acopia, obtenido de listar_proveedores' },
      { nombre: 'producto_referencia', label: 'Producto de referencia', requerido: true, descripcion: 'Nombre del producto que se acopia (ej. "Cemento") — se busca o se crea solo por nombre, no hace falta averiguar su id' },
      { nombre: 'unidad_medida', label: 'Unidad de medida', requerido: false, descripcion: 'Ej. "kg", "bolsa", "unidad" — si se omite y el producto ya existe, se usa la que ya tenga' },
      { nombre: 'saldo_inicial', label: 'Cantidad acopiada', requerido: true, descripcion: 'Cantidad del producto de referencia que representa este acopio (número)' },
      { nombre: 'monto_pagado', label: 'Monto pagado', requerido: true, descripcion: 'Monto que se le pagó al proveedor por adelantado por este acopio — genera un gasto ya marcado como Pagado, no pendiente' },
      { nombre: 'moneda', label: 'Moneda', requerido: false, opciones: ['ARS', 'USD'], descripcion: 'Si se omite, ARS' },
      { nombre: 'precio_referencia_inicial', label: 'Precio de referencia inicial', requerido: false, descripcion: 'Precio unitario del producto de referencia en este acopio — si se omite, se calcula solo como monto_pagado / saldo_inicial' },
      { nombre: 'fecha', label: 'Fecha', requerido: false, descripcion: 'Formato YYYY-MM-DD — si se omite, hoy' },
      { nombre: 'notas', label: 'Notas', requerido: false },
      { nombre: 'resumen', label: 'Resumen', requerido: true, descripcion: 'Frase corta y legible, ej. "Acopio de 500kg de Cemento con Proveedor ABC — $1.000.000 ARS pagados". Es lo único que el usuario lee para verificar antes de confirmar, los ids no se muestran.' },
    ],
  },
  retiro_acopio: {
    key: 'retiro_acopio',
    label: 'Retiro de un acopio',
    modulo: 'compras',
    rutaNavegacion: '/admin/compras?tab=acopios',
    campos: [
      { nombre: 'acopio_id', label: 'Acopio', requerido: true, descripcion: 'Id real del acopio, obtenido de listar_acopios' },
      { nombre: 'producto_nombre', label: 'Producto retirado', requerido: true, descripcion: 'Nombre del producto que se retira — puede ser el mismo producto de referencia del acopio (retiro 1:1), u otro que el proveedor también cubra (se convierte de valor con precio_retiro/precio_referencia). Se busca o se crea solo por nombre.' },
      { nombre: 'cantidad', label: 'Cantidad', requerido: true, descripcion: 'Cantidad retirada (número)' },
      { nombre: 'precio_retiro', label: 'Precio del producto retirado', requerido: false, descripcion: 'Obligatorio SOLO si el producto retirado es distinto al de referencia del acopio — precio unitario del producto que se está retirando, para convertir el valor' },
      { nombre: 'precio_referencia', label: 'Precio del producto de referencia', requerido: false, descripcion: 'Obligatorio SOLO si el producto retirado es distinto al de referencia — precio unitario del producto de referencia del acopio, para la misma conversión' },
      { nombre: 'obra_id', label: 'Proyecto destino', requerido: false, descripcion: 'Id real del proyecto al que va el stock retirado, obtenido de listar_proyectos — si se omite, va al pool de la empresa' },
      { nombre: 'notas', label: 'Notas', requerido: false },
      { nombre: 'resumen', label: 'Resumen', requerido: true, descripcion: 'Frase corta y legible, ej. "Acopio #3 — retiro de 100kg de Cemento". Es lo único que el usuario lee para verificar antes de confirmar, los ids no se muestran.' },
    ],
  },
}
